version: "2.1"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SIMPLE_SETTINGS: instance.local
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5
